### PR TITLE
Feature/thereisapulse

### PR DESCRIPTION
**Pull request by jiangeyre**
# Description
Added Pulse Chart to project single view display. Added error handling as well.

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## Change Status

- [x] Complete, tested, ready to review and merge

# How Has This Been Tested?

- [x] This works on my computer.
- [x] This works on the pair programmer's computer as well.

# Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My code has been reviewed by at least one peer
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] There are no merge conflicts

### CODE REVIEW

**Review by Cireimu — COMMENTED** [review]
Seems to function correctly, no new errors seem to be appearing either. Only thing I'd say is that there's some console logs still in there that might need to be removed, otherwise it's looking pretty good!

**Comment by RobertDGordon** [comment]
@Cireimu I've searched for a console.log and the only result is in settings/columnsettings/index 2.jsx

It looks like PR #250 by @Hammurobbie  is going to remove this.

**Review by RobertDGordon — APPROVED** [review]
Code has been tested on Win10 machine.  Many console warnings removed, looks good.

**Review by Trip4077 — APPROVED** [review]
Looks great, nice job with the small, clean PR!

**Review by JacobWashburn — APPROVED** [review]
everythings working and looks good. like the information being displayed.

**Pull request merged**
