### PR TITLE
Fixed infinite loop, now = finite loop

### PR DESCRIPTION
**Pull request by jiangeyre**
# Description

Fixed infinite loop.

## Type of change

Please delete options that are not relevant.

- [X] Bug fix (non-breaking change which fixes an issue)

## Change Status

- [X] Complete, tested, ready to review and merge

# How Has This Been Tested?

- [x] Test A
- [x] Test B

# Checklist

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] My code has been reviewed by at least one peer
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [X] There are no merge conflicts

### CODE REVIEW

**Review by Trip4077 — APPROVED** [review]
- Confirmed that change fixes infinite loop on Windows10 Home Edition via Network Tab in Browser Console

- Confirmed with team that change fixes loop on their machines as well

**Comment by jiangeyre** [comment]
Screen Shot 2020-03-11 at 10 56 56 AM

- This is what the Network tab in 'inspect' looks like without id placed on line 33 of index.js in Project/Queries. There is an endless loop.

```
export const NOTE_FEED_QUERY = gql`
  query NoteFeed($id: ID!, $privatePerm: Boolean) {
    me {
      id
      email
    }
    project(id: $id) {
      
      projectManagers {
        name
        id
        email
        avatar
      }
      notes(orderBy: updatedAt_DESC, privatePerm: $privatePerm) {
        id
        topic
        content
        author {
          id
          email
          name
        }
        attendedBy {
          id
          name
          email
          avatar
        }
        rating
        privateNote
      }
    }
  }
`;
```


Screen Shot 2020-03-11 at 10 56 41 AM

- This is what it looks like once id is added. The infinite loop is fixed.

```
export const NOTE_FEED_QUERY = gql`
  query NoteFeed($id: ID!, $privatePerm: Boolean) {
    me {
      id
      email
    }
    project(id: $id) {
      id
      projectManagers {
        name
        id
        email
        avatar
      }
      notes(orderBy: updatedAt_DESC, privatePerm: $privatePerm) {
        id
        topic
        content
        author {
          id
          email
          name
        }
        attendedBy {
          id
          name
          email
          avatar
        }
        rating
        privateNote
      }
    }
  }
`;
```

**Comment by RobertDGordon** [comment]
Without `id` in the NOTE_FEED_QUERY (will continue infinitely):
noID

With _id_ in NOTE_FEED_QUERY:
addedID

This is an infinite loop, and different issue than a re-render caused by nested components and associated queries.  @lawsonarichard and I discussed this last night.

**Review by Memitaru — APPROVED** [review]
👍 Pulled it down and seems to be working on Windows 10 Pro

**Pull request merged**
