### PR TITLE
Refactoring Master for Labs19

### PR DESCRIPTION
**Pull request by Vyraal1**
# Description
* Projects List View
* Project View
* Sidebar
* Moved Routes to Authorization Root
* Implement Layout Component

## Type of change

- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Change Status

- [x] Complete, but not tested (may need new tests)

# Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My code has been reviewed by at least one peer
- [x] My changes generate no new warnings
- [x] There are no merge conflicts

### CODE REVIEW

**Comment by ghost** [comment]
Looks good, reviewed code collectively as we were combining the views into the Layout view.

Outstanding issues that need discussing:

* Solution for state management for component-level functions

* Comments to outline the relatively confusing authentication flow

**Review by roywakumelojr — APPROVED** [review]
All the new projects updates look good.

**Review by frescocodes — APPROVED** [review]
Everything looks good so far.

**Comment by ghost** [comment]
Code was reviewed collectively as we were composing the views.

Looks good, everything is lining up nicely with the UX files.

**Review by ghost — APPROVED** [review]

**Pull request merged**
