### PR TITLE
Feature/display label persist

### PR DESCRIPTION
**Pull request by Hammurobbie**
# Description

Allows users to pick a label for each column/row and ensures that it persists. This branch will require a BE PR to work. Pull from 'feature/label-persist' in the BE repo.

Accompanying BackEnd PR: https://github.com/Lambda-School-Labs/mission-control-be/pull/120 

I'm passing in an object where our semantic UI component wants a value in two places, which is making our console unhappy. You'll notice a few console errors, but it shouldn't be breaking anything. We plan to clean these up in a later PR, but given our limited time, we'd like to go ahead and merge to master and make sure everything is working in staging as soon as possible.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Change Status

- [ ] Complete, tested, ready to review and merge
- [x] Complete, but not tested (may need new tests)
- [ ] Incomplete/work-in-progress, PR is for discussion/feedback

# How Has This Been Tested?

- [ ] Test A
- [ ] Test B

# Checklist

- [x] I have performed a self-review of my own code
- [x] My code has been reviewed by at least one peer
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] There are no merge conflicts

### CODE REVIEW

**Comment by RobertDGordon** [comment]
Checkout out this PR right now, @BryanKAdams and I had some of the same merge conflicts earlier today with the notes.  Should be able to help you sort those out too.

**Comment by RobertDGordon** [comment]
Warning message is coming from the query on the backend expecting an array of labels:
` createStatus(name: String!, projects: [String], id: ID!, labels: [String]): Status!`

But your query/mutation on the front end is only sending id and name:
```
    createStatus(id: $id, name: $name) {
      id
      name
    }
```

**Comment by Hammurobbie** [comment]
> Warning message is coming from the query on the backend expecting an array of labels:
> ` createStatus(name: String!, projects: [String], id: ID!, labels: [String]): Status!`
> 
> But your query/mutation on the front end is only sending id and name:
> 
> ```
>     createStatus(id: $id, name: $name) {
>       id
>       name
>     }
> ```

Good eye! It was our original plan to allow the program manager to make labels in the same modal as the "create status" modal, which is why it's asking for a labels array, but since the labels need a status id, we weren't able to make this happen given our state issues that we were having when we created that feature. Now that we've got that sorted out, we should be able to add that feature fairly easily in the near future to remove this warning and sauce up the user flow.

**Comment by RobertDGordon** [comment]
Other error messages:` Warning: Failed prop type: Invalid prop options[0].value supplied to Dropdown.`

Might want to check out this to help troubleshoot: https://github.com/mui-org/material-ui/issues/10845

**Comment by Cireimu** [comment]
[Label drop down selection persist](https://trello.com/c/txhhmazb/7-label-drop-down-selection-persist)

**Review by abdirahmanfarah — APPROVED** [review]

**Review by D-Fink — APPROVED** [review]

**Review by RobertDGordon — DISMISSED** [review]
The errors and warnings are still showing up:

```
react_devtools_backend.js:6 Invalid undefined: The field at `labels` is `undefined`, but the GraphQL query expects a selection set for this field.
(Caused At: "createStatusMutation" mutation, Unnamed query, Unnamed query)

react_devtools_backend.js:6 Invalid undefined: The field at `selected` is `undefined`, but the GraphQL query expects a selection set for this field.
(Caused At: "CreateLabelMutation" mutation, Unnamed query, Unnamed query)

index.js:1 Warning: Failed prop type: Invalid prop `options[0].value` supplied to `Dropdown`.
```

**Review by abdirahmanfarah — APPROVED** [review]

**Comment by RobertDGordon** [comment]
I've tried to debug the branch, it seems the queries on the front end `PROJECT_LIST_VIEW` and `LABEL_LIST_VIEW` do not match what is set up on the back end.  I was able to get the branch to load by removing `id` and `name` under the `selected` subset as they are not present on the back end.  However, when trying to save a list, it results in another error visible in the network tab of the dev tools:

`{"errors":[{"message":"Variable \"$id\" of required type \"ID!\" was not provided.","locations"`

**Comment by Hammurobbie** [comment]
> I've tried to debug the branch, it seems the queries on the front end `PROJECT_LIST_VIEW` and `LABEL_LIST_VIEW` do not match what is set up on the back end. I was able to get the branch to load by removing `id` and `name` under the `selected` subset as they are not present on the back end. However, when trying to save a list, it results in another error visible in the network tab of the dev tools:
> 
> `{"errors":[{"message":"Variable \"$id\" of required type \"ID!\" was not provided.","locations"`

So this isn't going to fix the code. Selected needs to have

> I've tried to debug the branch, it seems the queries on the front end `PROJECT_LIST_VIEW` and `LABEL_LIST_VIEW` do not match what is set up on the back end. I was able to get the branch to load by removing `id` and `name` under the `selected` subset as they are not present on the back end. However, when trying to save a list, it results in another error visible in the network tab of the dev tools:
> 
> `{"errors":[{"message":"Variable \"$id\" of required type \"ID!\" was not provided.","locations"`

I appreciate you trying to help, but this is not a proper fix. Selected needs to return at least one value from Project, so your change breaks the code. We are using the id that is being returned, so the feature won't work without it in the query, too. I'm guessing there may be something missing on the backend that may be causing this branch to break on your end. Also, one of your commits pushed the managers file back into the code, so we will need to purge this branch again.

Moving forward, it's probably best not to push your commits on someone else's branch, especially one from another team, without first reaching out to the person who created it. Once again, I appreciate the time you've taken to review this code. Maybe we can pull you in a zoom later to resolve the issues on your machine.

**Comment by RobertDGordon** [comment]
Thanks for the reply, the push was not intended to fix the code, apologies for the confusion/intrusion there.  (I've now tagged you in the thread in slack @Hammurobbie )

However, id's must be added to all subsets on queries, to prevent warnings and errors, or an infinite loop.   Perhaps you can update the backend to these specifications.

**Comment by RobertDGordon** [comment]
@Hammurobbie regarding the managers file, I've looked into it more and it seems your branch has not been filtered correctly.  A filter-branch command removes all commit history, however your force push from 4 days ago, `Hammurobbie force-pushed the feature/display-label-persist branch from a2cc3a6 to c47b131 4 days ago` still has the history of the deleted file despite the next commit `test after purge` not showing the file.  See the following link:
https://github.com/Lambda-School-Labs/mission-control-fe/compare/a2cc3a613abb8f52ffb3cb50446170d73fa85b73..c47b131e569cf271e434925770a8d397ba45d7ee

Also, your most recent force push (https://github.com/Lambda-School-Labs/mission-control-fe/compare/62ed76b14407009fa1fe5d15f673787e77df3bd5..79e9598162b531dcfbf4e656bfe5a48eb7d059b4) still contains the file information.

**Review by Trip4077 — APPROVED** [review]

**Review by lawsonarichard — APPROVED** [review]
Pulled down with need BE
Created a column, created labels. They persisted! 

OS: MAC OS

**Pull request merged**
