### PR TITLE
Feature/GitHub mutation

### PR DESCRIPTION
**Pull request by JacobWashburn**
# feature to save github repos to the backend
## uses the backend branch "feature/GitHub mutation"

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

## Change Status

- [x] Complete, tested, ready to review and merge
- [ ] Incomplete/work-in-progress, PR is for discussion/feedback

# Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My code has been reviewed by at least one peer
- [x] My changes generate no new warnings
- [x] There are no merge conflicts

### CODE REVIEW

**Review by jiangeyre — APPROVED** [review]
Downloaded changes locally. Works on my end.  Great mutation code.

**Review by BryanKAdams — APPROVED** [review]
Awesome code. Works well on my machine.

**Review by Trip4077 — APPROVED** [review]
Nice small PR!! Very clean work, only comment is add `target="_blank"` to the "Go To Analysis" link. Since we are linking to an external site, we want a new tab to open so the user can navigate code climate without having to go back forever or start over where they were on Mission Control

**Review by RobertDGordon — APPROVED** [review]
Added `target="_blank"` as per @Trip4077 's suggestion, as well as `rel="noopener noreferrer"` and tested external links.  No issues here, awesome work!

**Love that we are working with live data now.**

**Comment by Memitaru** [comment]
[GitHub Mutation](https://trello.com/c/WjhucV7E/2-github-mutation)

**Pull request merged**
