### PR TITLE
Feature/Delete Github Repos

### PR DESCRIPTION
**Pull request by RobertDGordon**
# Description

Adds the ability to select a repo to delete.  Corresponds with back end PR #122 
https://github.com/Lambda-School-Labs/mission-control-be/pull/122

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

## Change Status

- [x] Complete, tested, ready to review and merge

# Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My code has been reviewed by at least one peer
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] There are no merge conflicts

### CODE REVIEW

**Comment by RobertDGordon** [comment]
[Delete GitHub Repos](https://trello.com/c/htFk5Qo7/6-delete-github-repos)

**Review by Trip4077 — APPROVED** [review]

**Comment by Trip4077** [comment]
Approved Pending AWS check

**Review by jiangeyre — APPROVED** [review]
This is the prettier code I was looking for.

**Review by lawsonarichard — APPROVED** [review]
pulled and tested with needed BE

added a few repos...
deleted a few repos.

Good to go!

tested on Mac OS

**Pull request merged**
