### PR TITLE
Made the Rocket Logo an SVG so it scales better and has transparency

### PR DESCRIPTION
**Pull request by BryanKAdams**
# Description
Update Logo to be an SVG instead of a PNG, better scaling and transparency.

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

## Change Status

- [x] Complete, tested, ready to review and merge

# Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] My code has been reviewed by at least one peer
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] There are no merge conflicts

### CODE REVIEW

**Review by Trip4077 — APPROVED** [review]
Thanks for the switch! Transparent SVGs are a huge preference of mine

**Comment by Trip4077** [comment]
Looks great, once merge conflict is resolved it should be ready to merge!

**Comment by lawsonarichard** [comment]
[Rocket Logo SVG](https://trello.com/c/tWwEO5t3/11-rocket-logo-svg)

**Comment by lawsonarichard** [comment]
Merge in latest master. Then should be good to go.

**Review by lawsonarichard — APPROVED** [review]
Pulled down tested after merge from master.

Made the SVG 200px. 

looks good!

**Pull request merged**
